/**
 * A MOCKED skip trace. Nothing here is a real contact detail.
 *
 * The story says owner contact details are attached when an opportunity is
 * created. The county roll publishes the owner of record and a mailing address
 * and nothing else - no phone, no email - so the honest options were to leave
 * every opportunity reading "not on file", or to model the step a team actually
 * takes next, which is to send the owner to a skip-trace vendor.
 *
 * This is that step with the vendor replaced by a deterministic function, on
 * exactly the convention lib/notify/providers.ts already uses for the messaging
 * providers: a real adapter shape, a simulated body, and a value no reader can
 * mistake for a live one.
 *
 * WHAT MAKES IT UNMISTAKABLE:
 *
 * - The email is on a `.invalid` domain. RFC 2606 reserves that TLD precisely
 *   so it can never resolve, and the domain says `mocked-skip-trace` in words.
 * - The phone is in the 555-0100 to 555-0199 range, which NANP reserves for
 *   fiction and which no carrier will ever route.
 * - The document carries `simulated: true`, a `provider` of `mocked-skip-trace`
 *   and a human-readable `label`, so anything reading the JSON sees it before
 *   it sees a value. The UI renders the label beside the fields, and the CSV
 *   export puts them in columns whose names end in `_simulated`.
 *
 * WHAT STAYS REAL: the mailing address. It comes from the roll, it is the
 * address a print house would actually post to, and it keeps the source system
 * and source url it was read from. It is deliberately kept in different fields
 * from these, and the drawer renders the two apart, because mixing a real
 * address into a block of invented contact details would make the real one
 * untrustworthy too.
 *
 * Deterministic, so the same parcel always produces the same pair: a demo can
 * be re-run and a screenshot still matches, and a test needs no stub.
 */

import { createHash } from "node:crypto";

import { SKIP_TRACE_PROVIDER, type MockedOwnerContact } from "./documents";

export { SKIP_TRACE_PROVIDER, type MockedOwnerContact };

/** The area code Duval County actually uses, so the shape reads correctly. */
const AREA_CODE = "904";

export const SKIP_TRACE_LABEL =
  "SIMULATED CONTACT - generated by a mocked skip trace, not a real phone number or email address";

function digestOf(propertyId: string, ownerName: string): string {
  return createHash("sha256")
    .update(`${SKIP_TRACE_PROVIDER}|${ownerName}|${propertyId}`)
    .digest("hex");
}

/**
 * The simulated contact for one owner of record on one parcel.
 *
 * Keyed on both, not on the owner alone: a skip trace is run against a person
 * at an address, and keying on the name alone would give two unrelated
 * SMITH JOHNs the same number, which is the sort of detail that makes a
 * simulation look careless.
 */
export function mockedOwnerContact(input: {
  propertyId: string;
  ownerName: string | null;
}): MockedOwnerContact {
  const ownerName = input.ownerName?.trim() || "owner of record";
  const digest = digestOf(input.propertyId, ownerName);

  // 00..99, inside the reserved 555-0100..555-0199 block.
  const line = Number.parseInt(digest.slice(0, 4), 16) % 100;

  return {
    simulated: true,
    provider: SKIP_TRACE_PROVIDER,
    label: SKIP_TRACE_LABEL,
    email: `owner-${digest.slice(0, 10)}@mocked-skip-trace.invalid`,
    phone: `(${AREA_CODE}) 555-01${String(line).padStart(2, "0")}`,
    derivedFrom: `${ownerName} at parcel ${input.propertyId}`,
    basis:
      "The Duval County roll publishes an owner of record and a mailing address and no telephone or email. A real deployment would call a skip-trace vendor here; this build does not, and generates a reserved address and a reserved number instead.",
  };
}

/** True for any value this module produced, checked rather than assumed. */
export function isMockedContact(value: unknown): value is MockedOwnerContact {
  if (!value || typeof value !== "object") return false;
  const candidate = value as { simulated?: unknown; provider?: unknown };
  return candidate.simulated === true && candidate.provider === SKIP_TRACE_PROVIDER;
}
